name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:    
      matrix:
        arch: [64]

    steps:
    # Install dependencies
    - name: Install libck, libcurl
      run: sudo apt-get install libck-dev libcurl4-openssl-dev
    - name: Install Cyclone
      run: |
        wget https://github.com/cyclone-scheme/binary-releases/raw/master/ubuntu-18.04-lts/cyclone-scheme_0.15_amd64.deb 
        sudo apt install ./cyclone-scheme_0.15_amd64.deb
      
    # Setup winds
    - uses: actions/checkout@v2
    - name: Build
      run: cyclone srfi/152.sld
    - name: Run tests
      run: |
        cyclone cyclone-test.scm
        ./cyclone-test
